### ISSUE TITLE
Sign all Procon.* assemblies (Strong Name)

### ISSUE THREAD

**Issue by phogue** [phogue/Potato#32]
I've again run into a security problem that could be easily handled if we could supply the StrongName to the AppDomain creation as a full trust library.

I've googled the argument a number of times, especially storing the the self signed private key in the public repository.

I think not providing the source code in full wouldn't be helpful for plugin developers and others that want to contribute to the project.

We may look at supplying a self-signed certificate in the source, just so the repository can be cloned and compiled with minimal effort, but then use a private key supplied from DigiCert to code sign releases.

**Comment by MorpheusXAUT** [comment]
Does Procon 2 not function properly without signed assemblies?
If it worked to the largest intent and signing is mostly for "security" reasons, we could also simply comment out the signing-part in the manifests, like e.g. MySQL does for their .NET connector. 
Otherwise, a "throwaway" key (definitely marked as such) and a trusted, but "secret" key for release signing would probably the easiest way to go.

**Comment by phogue** [comment]
Nah I actually tried this on a local branch and it didn't fix it the way I thought it would. It fixes part of it and it's possible to have it work entirely, but it would defeat the proper isolation I was working towards with plugins. I'll try and work out the issue today and see if we can avoid signing the assemblies.

At the moment we have three (or more) AppDomain's.
- A) Program
- B) Service
- C..Z) Plugin (per connection)

The trouble is with B->C. At the moment if a command is sent from B->C, then during that method execution the plugin callbacks from C->B then for some reason I'm being inhibited by the plugins permission set, even though everything is telling me I'm in B's AppDomain and I have unrestricted permissions on the current AppDomain.

If I set unrestricted permissions to the plugin AppDomain then the callback reports full permissions and loading/using the SQLite library works as expected.

See http://stackoverflow.com/questions/18375868/cross-appdomain-callback-lost-permissions for a similar problem.

I'm pretty sure I've missed or misinterpreted a dot point in some obscure documentation about how remoting works, but I figured even if the command originated from the plugin AppDomain once execution had entered the host AppDomain you would be working with the hosts' permissions?

**Comment by MorpheusXAUT** [comment]
I suspect it might actually detect crossing appdomains and thus lower all permissions to the "lowest values" to provide better security, since programs could otherwise maybe "escalate" their permissions by abusing some of the "higher" appdomains... Does that make sense?

Basically: B has permissions 1, 2, 3 and 4, C just has 1 and 2 though. Calls then get made from B->C and C->B, which gets detected by the .NET framework, which then (temporarely) reduce's B's permissions to 1 and 2 only (so C cannot "escalate" privileges).

EDIT: that's just a guess though, I honestly don't know a real answer to this.

**Comment by phogue** [comment]
The trouble is you have to go out of your way to give access via an interface, so it's kind of difficult to accidentally give access to a plugin.

It's also problematic that AppDomain.CurrentDomain is reporting the host domain with the host permission set, so it's saying one thing buy doing another.

I had a theory as I was going to sleep last night that perhaps all loaded assemblies will have the lowest permission set during communication, so I moved/cleaned up the source a lot, moving models/interfaces to their own "Shared" type assemblies.

Plugins no longer load or know of Procon.Core, only three assemblies Procon.Net.Shared, Procon.Core.Shared and Procon.Database.Shared which just store simple objects and interfaces used by their assemblies. Still no luck.

**Comment by MorpheusXAUT** [comment]
> I had a theory as I was going to sleep last night that perhaps all loaded assemblies will have the lowest permission set during communication, so I moved/cleaned up the source a lot, moving models/interfaces to their own "Shared" type assemblies.

Yeah, that's what I was trying to say too, I guess that's a security feature by the .NET framework.

Trying to "circumvent" it by creating the *.Share libraries probably fails cause it detect your attempt to "outrun" security. I'll see if I can find anything regarding that too, but don't expect results before New Year...

**Comment by phogue** [comment]
I was more seeing if the loaded assemblies within the AppDomain were always constrained to the limited permission set, even if we're within the host AppDomain.

We're not, but the experiment has yielded a much better structure for Procon that no longer requires plugins to pretty much load Procon themselves.

I must be missing something or I've completely misunderstood how permissions are handled in 4.0+.

I've been tempted a couple times now to implement asynchronous commands from the AppDomain, have them stored on Procon's side and picked up by a worker thread that was run in host AppDomain to then execute the commands.

This would have the benefit of plugins not blocking the main thread in Procon. It also shows just how much nodejs I've been using recently.

Instead of:

```
// Blocking
CommandResultArgs result = this.Bubble(... command ... );'

// Do stuff with result
```

Enforce:

```
// Non-Blocking
this.BeginBubble(... command ..., result => {
// Do stuff with result..
});
```

This may get around all security issues we have without ever needing to give more permissions to the plugin AppDomain directly, while also simply making plugin development better.

**Comment by MorpheusXAUT** [comment]
So basically instead of forcing Procon to execute the action immediately (as it is currently), we're scheduling all tasks and adding them to an (asynchronous) execution list?
Sounds good if it helps prevent security problems, however we'd have to make sure they get executed quite quickly since some plugins might rely on the actions being executed before continuing with their own execution. Also, having action which should return values could get a bit more complicated, since we'd have to have a callback or something like this for Procon to pass the information back...

**Comment by MorpheusXAUT** [comment]
Ignore the callback part. It's morning and I didn't read your code sample properly :-)

**Comment by phogue** [comment]
So I wrote the asynchronous controller which either sends commands and has a callback, or can be used in place of the current controller with the same parameters and will block, but on the plugin side of the AppDomain. So a plugin can block if it prefers to write code that way, but it will be handled in the background in a thread.

I have it working with all tests passing but I think I need to write a few tests for this before I do a push tomorrow. I didn't end up having to sign the assemblies, so we're still working with vanilla, which is nice and easy.

No matter what, once the plugin's callback crosses the AppDomain it will now be added to a queue of pending commands and picked up by a thread that was started in Full Trust. So we don't have to worry about commands and security concerns anymore, plus we can write all sorts of functionality for a plugin to use without the end-user needing to worry about the sandbox permissions.

**Comment by phogue** [comment]
Closed. Solution to problem found without needing to use signed libraries. This topic may come up again in the future though.
